#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_animation_duration    0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.92
yabai -m config window_border                off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xffC6A0F6
yabai -m config normal_window_border_color   0xffC5CFF5
yabai -m config insert_feedback_color        0xffC6A0F6
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0 
yabai -m config bottom_padding               8 
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add title="^$" manage=off

# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:45:00

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
#yabai -m config external_bar builtin:10:0

echo "yabai configuration loaded.."
